name: client
type: "java:8"
disk: 800
hooks:
  build: mvn -Dhttp.port=8888 -Dspeaker.service=http://speaker.internal/ -Dconference.service=http://conference.internal/ -Dsession.service=http://session.internal/ -DskipTests clean install tomee:exec

mounts:

    '/.distribution':
        source: local
        source_path: tomee_source

    '/app':
        source: local
        source_path: tomee_source

relationships:
   speaker: speaker:http
   conference: conference:http
   session: session:http

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: |
          mv target/ROOT-exec.jar app/ROOT-exec.jar
          java -jar $JAVA_OPTS app/ROOT-exec.jar
