# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: client

# The runtime the application uses.
type: "java:8"

disk: 800

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      wget -P parent/pom.xml https://raw.githubusercontent.com/EventosJEspanol/latin-america-micro-profile/master/pom.xml
      mvn clean install -U -N -f parent/pom.xml
      mvn -Dhttp.port=8888 -DskipTests clean install tomee:exec

mounts:

    '/.distribution':
        source: local
        source_path: tomee_source

    '/app':
        source: local
        source_path: tomee_source

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
   speaker: speaker:http
   conference: conference:http
   session: session:http

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: |
          mv target/ROOT-exec.jar app/ROOT-exec.jar
          java -Xmx1024m -jar -Dorg.jespanol.client.speaker.SpeakerService/mp-rest/url=http://speaker.internal/ -Dorg.jespanol.client.conference.ConferenceService/mp-rest/url=http://conference.internal/ -Dorg.jespanol.client.session.SessionService/mp-rest/url=http://session.internal/ app/ROOT-exec.jar
