name: conference
type: "java:8"
disk: 800
hooks:
  build: mvn -U -DskipTests clean package payara-micro:bundle
relationships:
  mongodb: 'mongodb:mongodb'
web:
    commands:
        start: java -jar $JAVA_OPTS $CREDENTIAL target/conference-microbundle.jar --port $PORT