name: speaker
type: "java:8"
disk: 800
hooks:
    build: mvn -U -DskipTests clean package thorntail:package
relationships:
  postgresql: 'postgresql:postgresql'
web:
    commands:
        start: java -jar  $JAVA_OPTS -Dswarm.http.port=$PORT -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true target/speaker-thorntail.jar

