name: session
type: "java:8"
disk: 800
hooks:
    build: mvn -DskipTests -U clean package kumuluzee:repackage
mounts:
    '/app':
        source: local
        source_path: app_source
relationships:
  elasticsearch: 'elasticsearch:elasticsearch'
web:
    commands:
        start: |
          mv target/session.jar app/session.jar
          java -jar $JAVA_OPTS $CREDENTIAL -Dkumuluzee.server.http.port=$PORT app/session.jar


